#!/bin/bash
# PR As A Service Script
# Aare Pajuste
#

### BEGIN INIT INFO
# Provides:          startprservers
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: PRServers Daemon.
# Description:       Starts all the PR servers/
### END INIT INFO

case "$1" in
start)
	### this is for the FTP service

	##merkpublic
	mount --bind /home/pr/prMain/admin/logs /var/www/prftp/chatlogs
	mount --bind /home/pr/prMain/mods/pr/demos /var/www/prftp/battlerecorder

	##merkadmin ftp
	mount --bind /home/pr/prMain/admin/logs /var/www/merkftp/logs
	mount --bind /home/pr/prMain/mods/pr/demos /var/www/merkftp/battlerecorder
	mount --bind /home/pr/prMain/mods/pr/settings /var/www/merkftp/settings
	mount --bind /backups   /var/www/merkftp/backups
				
				
        echo "Starting all the PR servers."

	service prmain start
	service prevent start
	service prtraining start
        ;;
stop)
        service prmain stop
	service prevent stop
	service prtraining stop
        ;;
restart)
	service prmain restart
	service prevent restart
	service prtraining restart
	;;
status)
	echo "Showing PR processes that are running"
	ps aux|grep -i prmurmurd
	ps aux|grep -i startmumo
	ps aux|grep -i start_server.sh
	ps aux|grep -i prbf2
	ps aux|grep -i tcpdump
	;;
*)
echo "The PR Server Service"
echo $"Usage: $0 {start|stop|status|restart}"
exit 1
esac
exit 0

